name: 

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: [ self-hosted ,iag10 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Create directory github
        run: mkdir /home/itential/github

      - name: Deploy to Server2
        run: |
         ssh user@server2.example.com '
           if [ ! -d "/home/itential/github/.git" ]; then
             git clone git@github.com:anupathaniagenpact/demo-01.git /home/itential/github/;
           else
             cd /home/itential/github && git pull origin main;
           fi
        
