name: CI sample

on:
  push:
    branches:
      - main


jobs:
  build: 
    runs-on: [ IAG10 ]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Run ansible script
        shell: bash 
        run: |
          cd /home/itential/ansible-playbooks/
          ansible-playbook -i inventory playbook.yml

          

    
        
