name: 

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: [ self-hosted ,iag10 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.IAG10_SSH_KEY }}

      - name: Create directory github
        run: echo "hello"

      - name: Deploy to Server2
        run: |
         ssh -t itential@182.94.235.62 << 'EOF'
           if [ ! -d "/home/itential/github/.git" ]; then
             git clone git@github.com:anupathaniagenpact/demo-01.git /home/itential/github/;
           else
             cd /home/itential/github && git pull origin main;
           fi
        
