name: CI sample

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: [ self-hosted ,iag10 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: anupathaniagenpact/demo-01.git
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          
      - name: Set Git remote to HTTPS (if it defaults to SSH)
        run: |
          git remote set-url origin https://github.com/anupathan/demo-01.git  # Replace with your repository
          git fetch
      - name: Create directory github
        run: echo "hello1"

      
        
