name: 

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: [ self-hosted ,iag10 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create directory github
        run: echo "hello1"

      
        
