name: CI sample

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: [ self-hosted ,iag10 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

          

    
        
