name: CI sample

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: [ self-hosted ,iag10 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: anupathaniagenpact/demo-01.git
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          

      - name: Create directory github
        run: echo "hello1"

      
        
